MoMMi-side of an automatic #ick lock after a round ends.
PJB3005/MoMMI pull request #42
Opened 2021-01-10 18:01 UTC by ShiftyRail

Need also to do a :
- Secret repo side of this (by adding #ick unique identifier to `server.toml` or whatever so that I can call `send2discord` with this identifier in Byond)
- BYOND side of this (send the magic string `"round_end_thread_remind"` to the `#ick` discord channel)

From a cursory look at MoMMi, what the documentation calls a `Guild` is `self.server` within the `MChannel` class, and what the documentation calls a `Channel` is the `discordpy_channel` attribute. 

I used a stackexchange bit of code to find what the `default_role` attribute and `set_permissions` method were.

Please tell me if I did anything wrong.

2021-01-10 18:10 UTC, SonixApache commented
trash idea

2021-01-10 18:13 UTC, boy2mantwicethefam commented
Incredibly powerful

2021-01-10 18:21 UTC, ShiftyRail commented
@PJB3005 Can you store user-defined variables in `server.toml` or is that file just for giving configuration info

2021-01-11 05:10 UTC, jwhitak commented
Discussion on Discord seems to overall favor this but with a shorter duration, 3 minutes has been mentioned a lot. I'm not personally for the PR, but the need for it to be there is understandable. The thread is the lifeblood of the server.

2021-01-12 17:14 UTC, PJB3005 requested changes

2021-01-12 17:14 UTC, PJB3005 commented on MoMMI/Modules/gamenudge.py
> +        thread_reminder(channel)
You're not actually importing this function from the other module.

2021-01-12 17:14 UTC, PJB3005 commented on MoMMI/Modules/thread_reminder.py
> +    await channel.send("**A round has ended.** You can discuss it at https://boards.4chan.org/vg/catalog#s=ss13g. This channel will be closed for 10 minutes.")
This says 10 minutes but you lowered it to 5 below.

2021-01-12 17:14 UTC, PJB3005 commented on MoMMI/channel.py
> +        await discordpy_channel.set_permissions(self.server.default_role, send_messages=True)
```suggestion
        await discordpy_channel.set_permissions(self.server.discordpy_server.default_role, send_messages=False)

    # Open it
    def open()
        await discordpy_channel.set_permissions(self.server.discordpy_server.default_role, send_messages=True)
```

2021-01-12 19:46 UTC, ShiftyRail commented
Done, also need whatever magic you use to convert the string "ick" into the identifier of the #ick channel.

2021-01-12 20:34 UTC, PJB3005 reviewed
Whoops forgot about these

2021-01-12 20:34 UTC, PJB3005 commented on MoMMI/Modules/thread_reminder.py
> +    time.sleep(300)
oh I almost forgot, you need to do `await asyncio.delay()` not `time.sleep()` here or else you'll lock up the whole bot.

2021-01-12 20:34 UTC, PJB3005 commented on MoMMI/channel.py
> +    def close()
```suggestion
    async def close():
```

2021-01-12 20:34 UTC, PJB3005 commented on MoMMI/channel.py
> +    def open()
```suggestion
    async def open():
```

2021-01-13 00:05 UTC, PJB3005 commented on MoMMI/channel.py
> +    async def open()
You forgot the colons here.

2021-01-13 00:05 UTC, PJB3005 commented on MoMMI/Modules/thread_reminder.py
> +import logging
And didn't import asyncio here.

2021-01-13 08:32 UTC, ShiftyRail commented
Thank you for your patience, PJB

2021-01-26 12:44 UTC, merged